name: Test dispatch

on:
  repository_dispatch:
    types: [test_result_dispatch]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Result action
        run: true
