name: Test dispatch

on:
  repository_dispatch:
    types: [test_result_dispatch]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create team sync issue
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          assignees: "nvdai2401"
          labels: "playwright-test-fail"
          title: "Playwright test failed"
          body: |
            ### Agenda
            Action: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            - [ ] Start the recording
            - [ ] Check-ins
            - [ ] Discussion points
            - [ ] Post the recording
                    
            ### Discussion Points
            Add things to discuss below

            - [Work this week](https://github.com/orgs/github/projects/3)
          pinned: true
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Result action
        run: true
